# Generated by Django 5.2.8 on 2025-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='look',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='look',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='look',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='look',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='look',
            name='productos',
        ),
        migrations.AddField(
            model_name='look',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='look',
            name='name',
            field=models.CharField(default='Nuevo look', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='look',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='look',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='look',
            name='tags',
            field=models.CharField(blank=True, help_text='Escribe etiquetas separadas por comas. Ej: boho, verano', max_length=200, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='look',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='looks/', verbose_name='Portada'),
        ),
    ]
