# Generated by Django 5.2.8 on 2025-12-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_producto_categoria_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='looks', to='catalog.producto'),
        ),
    ]
