# Generated by Django 6.0 on 2025-12-06 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_look_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.look')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_items', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'Prenda del look',
                'verbose_name_plural': 'Prendas del look',
            },
        ),
    ]
